// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Powertronic.Data;

#nullable disable

namespace Powertronic.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260610220233_Baseline")]
    partial class Baseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Powertronic.Models.Adquisicion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int")
                        .HasColumnName("Empleado_Id");

                    b.Property<DateTime>("FechaAdquisicion")
                        .HasColumnType("datetime2")
                        .HasColumnName("Fecha");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Num_Documento");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("int")
                        .HasColumnName("Proveedor_Id");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Total");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("ProveedorId");

                    b.ToTable("Adquisicion");
                });

            modelBuilder.Entity("Powertronic.Models.Cargo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Descripcion");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("Estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("Fecha_Creacion");

                    b.Property<string>("NombreCargo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NombreCargo");

                    b.HasKey("Id");

                    b.ToTable("Cargo");
                });

            modelBuilder.Entity("Powertronic.Models.CategoriaProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("Estado");

                    b.Property<string>("NombreCategoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nombre");

                    b.HasKey("Id");

                    b.ToTable("CategoriaProducto");
                });

            modelBuilder.Entity("Powertronic.Models.Clientes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApellidoCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Apellidos");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Cedula");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Direccion");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("Estado");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2")
                        .HasColumnName("Fecha_Creacion");

                    b.Property<string>("Gmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Gmail");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nombres");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Telefono");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Powertronic.Models.Despacho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientesId")
                        .HasColumnType("int")
                        .HasColumnName("Cliente_Id");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int")
                        .HasColumnName("Empleado_Id");

                    b.Property<DateTime>("FechaFactura")
                        .HasColumnType("datetime2")
                        .HasColumnName("Fecha");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Num_Factura");

                    b.Property<int>("TipoPagoId")
                        .HasColumnType("int")
                        .HasColumnName("TipoPago_Id");

                    b.Property<decimal>("TotalFactura")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Total");

                    b.Property<int>("Venta_ProdId")
                        .HasColumnType("int")
                        .HasColumnName("Venta_Prod_Id");

                    b.HasKey("Id");

                    b.HasIndex("ClientesId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("Venta_ProdId");

                    b.ToTable("Despacho");
                });

            modelBuilder.Entity("Powertronic.Models.Det_Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("Cantidad");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int")
                        .HasColumnName("Producto_Id");

                    b.Property<decimal>("TotalVenta")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Total");

                    b.Property<int>("Venta_ProdId")
                        .HasColumnType("int")
                        .HasColumnName("Venta_Prod_Id");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("Venta_ProdId");

                    b.ToTable("Det_Venta");
                });

            modelBuilder.Entity("Powertronic.Models.Detalle_Adquisicion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdquisicionId")
                        .HasColumnType("int")
                        .HasColumnName("Adquisicion_Id");

                    b.Property<decimal>("PrecioAdquisicion")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PrecioAdquisicion");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int")
                        .HasColumnName("Producto_Id");

                    b.Property<int>("Stock")
                        .HasColumnType("int")
                        .HasColumnName("Stock");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Total");

                    b.HasKey("Id");

                    b.HasIndex("AdquisicionId");

                    b.HasIndex("ProductoId");

                    b.ToTable("Detalle_Adquisicion");
                });

            modelBuilder.Entity("Powertronic.Models.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Apellidos");

                    b.Property<int>("CargoId")
                        .HasColumnType("int")
                        .HasColumnName("Cargo_Id");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Cedula");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CodigoEmpleado");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Direccion");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("Estado");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2")
                        .HasColumnName("Fecha_Creacion");

                    b.Property<string>("Gmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Gmail");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nombres");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Telefono");

                    b.HasKey("Id");

                    b.HasIndex("CargoId");

                    b.ToTable("Empleado");
                });

            modelBuilder.Entity("Powertronic.Models.Orden_Reparacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CostoReparacion")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Costo");

                    b.Property<int>("DespachoId")
                        .HasColumnType("int")
                        .HasColumnName("Factura_Id");

                    b.Property<string>("DetallesReparacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Det_Reparacion");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int")
                        .HasColumnName("Empleado_Id");

                    b.Property<bool>("EstadoEntrega")
                        .HasColumnType("bit")
                        .HasColumnName("EstadoEntrega");

                    b.Property<DateTime>("FechaEntrega")
                        .HasColumnType("datetime2")
                        .HasColumnName("Fecha_Entrega");

                    b.Property<DateTime>("FechaOrden")
                        .HasColumnType("datetime2")
                        .HasColumnName("Fecha_Orden");

                    b.HasKey("Id");

                    b.HasIndex("DespachoId");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("Orden_Reparacion");
                });

            modelBuilder.Entity("Powertronic.Models.Pago_Tarjeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoAutorizacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CodigoAutorizacion");

                    b.Property<int>("DespachoId")
                        .HasColumnType("int")
                        .HasColumnName("Despacho_Id");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaPago");

                    b.Property<string>("MarcaTarjeta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MarcaTarjeta");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Monto");

                    b.Property<string>("Ultimos4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Ultimos4");

                    b.HasKey("Id");

                    b.HasIndex("DespachoId");

                    b.ToTable("Pago_Tarjeta");
                });

            modelBuilder.Entity("Powertronic.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoriaProducto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CategoriaProducto_Id");

                    b.Property<int?>("CategoriaProductoId")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CodigoProducto");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("Estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("Fecha_Creacion");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Imagen");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NombreProducto");

                    b.Property<decimal>("PrecioCompra")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PrecioCompra");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PrecioVenta");

                    b.Property<int>("ProveedoresId")
                        .HasColumnType("int")
                        .HasColumnName("Proveedores_Id");

                    b.Property<int>("StockDisponible")
                        .HasColumnType("int")
                        .HasColumnName("Stock");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaProductoId");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("Powertronic.Models.Proveedores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CodigoProveedor");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Direccion");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("Estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NombreProveedor");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Telefono");

                    b.HasKey("Id");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("Powertronic.Models.TipoPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("Estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Tipos_Pago");
                });

            modelBuilder.Entity("Powertronic.Models.Venta_Prod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("Fecha");

                    b.Property<decimal>("TotalVenta")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Total");

                    b.HasKey("Id");

                    b.ToTable("Venta_Prod");
                });

            modelBuilder.Entity("Powertronic.Models.Adquisicion", b =>
                {
                    b.HasOne("Powertronic.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Powertronic.Models.Proveedores", "Proveedor")
                        .WithMany("adquisiciones")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Powertronic.Models.Despacho", b =>
                {
                    b.HasOne("Powertronic.Models.Clientes", "Clientes")
                        .WithMany()
                        .HasForeignKey("ClientesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Powertronic.Models.Empleado", "Empleado")
                        .WithMany("despachos")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Powertronic.Models.Venta_Prod", "Venta_Prod")
                        .WithMany()
                        .HasForeignKey("Venta_ProdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clientes");

                    b.Navigation("Empleado");

                    b.Navigation("Venta_Prod");
                });

            modelBuilder.Entity("Powertronic.Models.Det_Venta", b =>
                {
                    b.HasOne("Powertronic.Models.Producto", "Producto")
                        .WithMany("Detalle_Ventas")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Powertronic.Models.Venta_Prod", "Venta_Prod")
                        .WithMany("det_Ventas")
                        .HasForeignKey("Venta_ProdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Venta_Prod");
                });

            modelBuilder.Entity("Powertronic.Models.Detalle_Adquisicion", b =>
                {
                    b.HasOne("Powertronic.Models.Adquisicion", "Adquisicion")
                        .WithMany()
                        .HasForeignKey("AdquisicionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Powertronic.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adquisicion");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Powertronic.Models.Empleado", b =>
                {
                    b.HasOne("Powertronic.Models.Cargo", "Cargo")
                        .WithMany("Empleados")
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cargo");
                });

            modelBuilder.Entity("Powertronic.Models.Orden_Reparacion", b =>
                {
                    b.HasOne("Powertronic.Models.Despacho", "Despacho")
                        .WithMany("orden_Reparacions")
                        .HasForeignKey("DespachoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Powertronic.Models.Empleado", "Empleado")
                        .WithMany("orden_Reparaciones")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Despacho");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("Powertronic.Models.Pago_Tarjeta", b =>
                {
                    b.HasOne("Powertronic.Models.Despacho", "Despacho")
                        .WithMany()
                        .HasForeignKey("DespachoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Despacho");
                });

            modelBuilder.Entity("Powertronic.Models.Producto", b =>
                {
                    b.HasOne("Powertronic.Models.CategoriaProducto", null)
                        .WithMany("productos")
                        .HasForeignKey("CategoriaProductoId");
                });

            modelBuilder.Entity("Powertronic.Models.Cargo", b =>
                {
                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("Powertronic.Models.CategoriaProducto", b =>
                {
                    b.Navigation("productos");
                });

            modelBuilder.Entity("Powertronic.Models.Despacho", b =>
                {
                    b.Navigation("orden_Reparacions");
                });

            modelBuilder.Entity("Powertronic.Models.Empleado", b =>
                {
                    b.Navigation("despachos");

                    b.Navigation("orden_Reparaciones");
                });

            modelBuilder.Entity("Powertronic.Models.Producto", b =>
                {
                    b.Navigation("Detalle_Ventas");
                });

            modelBuilder.Entity("Powertronic.Models.Proveedores", b =>
                {
                    b.Navigation("adquisiciones");
                });

            modelBuilder.Entity("Powertronic.Models.Venta_Prod", b =>
                {
                    b.Navigation("det_Ventas");
                });
#pragma warning restore 612, 618
        }
    }
}
